# Generated by Django 5.0.4 on 2025-02-01 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('grow_days', models.IntegerField(verbose_name='Срок созревания (дни)')),
                ('expire_days', models.IntegerField(verbose_name='Срок годности (дни)')),
                ('grams_per_tray', models.IntegerField(default=0, verbose_name='Грамм на лоток')),
                ('soaking_required', models.BooleanField(default=False, verbose_name='Замачивание')),
                ('press_weight', models.CharField(choices=[('0.5', '0.5 кг'), ('1', '1 кг')], default='0.5', max_length=10, verbose_name='Прижим (кг)')),
                ('germination_days', models.IntegerField(default=3, verbose_name='Дней на прорастание (20°C)')),
                ('light_days', models.IntegerField(default=5, verbose_name='Дней на свету')),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата посадки')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='Дата созревания')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('status', models.CharField(choices=[('growing', 'Растет'), ('ready', 'Созрело'), ('expired', 'Просрочено')], default='growing', max_length=10, verbose_name='Статус')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.culture', verbose_name='Культура')),
            ],
        ),
    ]
