# Generated by Django 5.0.4 on 2025-02-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planting',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='planting',
            name='sale_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Крайний срок продажи'),
        ),
    ]
